# Generated by Django 2.1.5 on 2019-02-05 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brandapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticketsetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(max_length=1000)),
                ('title', models.TextField(max_length=1000)),
                ('description', models.TextField(max_length=5000)),
                ('summary', models.TextField(max_length=5000)),
                ('priority', models.TextField(max_length=1000)),
                ('pimage', models.FileField(default='media/blank.png', upload_to='media')),
                ('request_takedown', models.BooleanField(default=False)),
                ('takedown_initiated', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='detectiontable',
            name='ticket_id',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='domains',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
