# Generated by Django 2.1.5 on 2019-02-05 09:10

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('brandapp', '0004_ticketsetting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsetting',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
