# Generated by Django 2.1.5 on 2019-02-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandapp', '0007_auto_20190205_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('bugid', models.IntegerField()),
                ('filenames', models.CharField(blank=True, max_length=600)),
                ('is_internal', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
