# Generated by Django 2.1.5 on 2019-02-05 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brandapp', '0008_commments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commments',
            old_name='bugid',
            new_name='ticketid',
        ),
    ]
