# Generated by Django 2.1.5 on 2019-02-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandapp', '0011_category_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
