# Generated by Django 2.1.5 on 2019-02-07 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brandapp', '0012_emailtemplate_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='whoisinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_detected', models.TextField(blank=True, max_length=1000)),
                ('registrant_email', models.TextField(blank=True, max_length=1000)),
                ('registrant_name', models.TextField(blank=True, max_length=1000)),
                ('registrant_organization', models.TextField(blank=True, max_length=1000)),
                ('registrant_telephone', models.TextField(blank=True, max_length=1000)),
                ('whoisServer', models.TextField(blank=True, max_length=1000)),
                ('createdDate', models.TextField(blank=True, max_length=1000)),
                ('registrant_country', models.TextField(blank=True, max_length=500)),
                ('registrant_state', models.TextField(blank=True, max_length=500)),
                ('detection_type', models.TextField(default='domain', max_length=10)),
                ('action_taken', models.BooleanField(default=False)),
                ('ticket_id', models.TextField(blank=True, default=None)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('original_domain', models.TextField(blank=True, max_length=1000)),
                ('ticketid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brandapp.ticketsetting')),
            ],
        ),
    ]
