# Generated by Django 2.1.5 on 2019-02-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brandapp', '0014_ticketsetting_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsetting',
            name='status',
        ),
    ]
