# Generated by Django 2.1.5 on 2019-02-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brandapp', '0017_auto_20190207_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsetting',
            name='status',
        ),
    ]
