# Generated by Django 2.1.5 on 2019-02-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brandapp', '0019_ticketsetting_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField(blank=True, max_length=5000)),
                ('msg', models.TextField(blank=True, max_length=5000)),
                ('ticketid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brandapp.ticketsetting')),
            ],
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='user',
        ),
        migrations.DeleteModel(
            name='notifications',
        ),
    ]
